studentfees/urls.py
from django.conf.urls import url
from django.contrib import admin

import core.views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^students/$', core.views.StudentListView.as_view(), name='student-list'),
    url(r'^students/create/$', core.views.StudentCreateView.as_view(), name='student-create'),
    url(r'^students/(?P<pk>[0-9]+)/update/$', core.views.StudentUpdateView.as_view(), name='student-update'),
    url(r'^students/(?P<pk>[0-9]+)/$', core.views.StudentDetailView.as_view(), name='student-detail'),
    url(r'^students/(?P<pk>[0-9]+)/delete/$', core.views.StudentDeleteView.as_view(), name='student-delete'),
    url(r'^payments/create/$', core.views.PaymentCreateView.as_view(), name='payment-create'),
    url(r'^payments/(?P<pk>[0-9]+)/delete/$', core.views.PaymentDeleteView.as_view(), name='payment-delete'),

]

core/models.py
from django.db import models
from django.urls import reverse


class Student(models.Model):

    """
    This class represents students
    """

    surname = models.CharField(

        max_length=64
    )

    forename = models.CharField(

        max_length=64
    )

    def __str__(self):

        return "{} {}".format(self.forename, self.surname)

    def get_absolute_url(self):

        return reverse('student-detail', args=[str(self.id)])


class Payment(models.Model):

    """
    This class represents payments of a specific student
    """

    student = models.ForeignKey(

        Student,
        on_delete=models.CASCADE,
        related_name='payment_list'
    )

    amount = models.DecimalField(

        decimal_places=2,
        max_digits=9
    )

    date = models.DateField(

    )

    def __str__(self):

        return "Student {} {}, date {}, and amount {}".format(self.student.forename, self.student.surname, self.date, self.amount)


    def get_absolute_url(self):

        return reverse('student-detail', args=[str(self.student.id)])

core/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from core.models import Student, Payment


class StudentListView(ListView):

    model = Student
    ordering = ['surname', 'forename']


class StudentDetailView(DetailView):
    model = Student


class StudentUpdateView(SuccessMessageMixin, UpdateView):
    model = Student
    fields = ['forename', 'surname']
    success_message = "Student record %(forename)s %(surname)s was updated successfully"


class StudentCreateView(SuccessMessageMixin, CreateView):
    model = Student
    fields = ['forename', 'surname']
    success_message = "Student record %(forename)s %(surname)s was created successfully"


class StudentDeleteView(DeleteView):
    model = Student
    success_url = reverse_lazy('student-list')


class PaymentCreateView(SuccessMessageMixin, CreateView):
    model = Payment
    fields = ['date', 'amount']
    success_message = "Payment record %(date)s and %(amount)s was created successfully"

    def form_valid(self, form):
        form_date = form.cleaned_data['date']
        form_amount = form.cleaned_data['amount']

        student_id = self.request.GET.get('student')
        student = Student.objects.get(pk=student_id)

        payment = Payment.objects.create(
            student=student,
            date=form_date,
            amount=form_amount
        )

        return redirect(payment.get_absolute_url())


class PaymentDeleteView(DeleteView):
    model = Payment
    success_url = reverse_lazy('student-list')

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Student fees</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
          integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="{% static 'core/datepicker/datepicker.min.css' %}" rel="stylesheet">
</head>
<body>

<div class="container">

    <br/>

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'student-list' %}">Home</a></li>
        </ol>
    </nav>

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script src="{% static 'core/datepicker/datepicker.min.js' %}"></script>

    {% block javascript %}
    {% endblock %}

</div>

</body>
</html>

core/templates/core/payment_confirm_delete.html
{% extends "core/base.html" %}

{% block content %}

<div class="card">
    <div class="card-header">
        <span>Payment details</span>
    </div>
    <div class="card-body">

        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" value="Confirm" class="btn btn-danger">
            <a href="{{ object.get_absolute_url }}" class="btn btn-success">Cancel</a>
        </form>


    </div>
</div>

{% endblock %}

core/templates/core/payment_form.html
{% extends "core/base.html" %}

{% block content %}
<div class="card">
    <div class="card-header">
        <span>New payment record</span>
    </div>
    <div class="card-body">
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.non_field_errors }}
            {{ form.date.errors }}
            {{ form.amount.errors }}
        </div>
        {% endif %}

        <form method="post" class="form-inline">{% csrf_token %}

            <div class="form-group">
                <label for="{{ form.date.id_for_label }}">Date:</label>&nbsp;
                <input type="text" name="date" required id="id_date" class="form-control" data-toggle="datepicker"/>&nbsp;
            </div>

            <div class="form-group">
                <label for="{{ form.amount.id_for_label }}">Amount:</label>&nbsp;
                <input type="number" name="amount" step="0.1" required id="id_amount" class="form-control"/>&nbsp;
            </div>

            <input type="submit" class="btn btn-primary" value="Save">&nbsp;
            <a href="{% url 'student-list' %}" class="btn btn-success">Cancel</a>

        </form>
    </div>
</div>

{% endblock %}

{% block javascript %}
<script>
    $().datepicker({
        format: 'yyyy-mm-dd'
    });

    $('[data-toggle="datepicker"]').datepicker();
</script>
{% endblock %}

core/templates/core/student_confirm_delete.html
{% extends "core/base.html" %}

{% block content %}

<div class="card">
    <div class="card-header">
        <span>Student details</span>
    </div>
    <div class="card-body">

        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" value="Confirm" class="btn btn-danger">
            <a href="{{ object.get_absolute_url }}" class="btn btn-success">Cancel</a>
        </form>


    </div>
</div>

{% endblock %}

core/templates/core/student_detail.html
{% extends "core/base.html" %}

{% block content %}


<div class="row">

    <div class="col-md-6">

        <div class="card">
            <div class="card-header">
                <span>Student details <i class="fas fa-user"></i></span>
            </div>
            <div class="card-body">

                <h5>{{ object }}</h5>
                <p>Surname: {{ object.surname }}</p>
                <p>Forename: {{ object.forename }}</p>

                <p>
                    <a href="{% url 'student-update' object.id %}" class="btn btn-primary">Update record <i class="fas fa-edit"></i></a>
                    <a href="{% url 'student-delete' object.id %}" class="btn btn-danger">Delete record</a>
                </p>

            </div>
        </div>

    </div>

    <div class="col-md-6">

        <div class="card">
            <div class="card-header">
                <span>Student payments <i class="fas fa-money-bill-wave"></i></span>
            </div>
            <div class="card-body">

                <table class="table table-hover table-sm">
                    <thead>
                    <tr>
                        <th>Date</th>
                        <th>Amount</th>
                        <th>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for payment in object.payment_list.all|dictsort:"date" %}

                    <tr>
                        <td>{{ payment.date|date:"Y-m-d" }}</td>
                        <td>{{ payment.amount }}</td>
                        <td><a href="{% url 'payment-delete' payment.id %}" class="btn btn-danger">Delete record</a></td>
                    </tr>

                    {% endfor %}

                    </tbody>
                </table>

                <p><a href="{% url 'payment-create' %}?student={{ object.id }}" class="btn btn-primary">Create new
                    payment</a>
                </p>

            </div>
        </div>
    </div>

</div>

{% endblock %}

core/templates/core/student_form.html
{% extends "core/base.html" %}

{% block content %}
<div class="card">
    <div class="card-header">
        <span>Student record</span>
    </div>
    <div class="card-body">
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.non_field_errors }}
            {{ form.date.errors }}
            {{ form.amount.errors }}
        </div>
        {% endif %}

        <form method="post" class="form-inline">{% csrf_token %}

            <div class="form-group">
                <label for="id_forename">Forename:</label>&nbsp;
                <input type="text" name="forename" maxlength="64" required id="id_forename" class="form-control" value="{{ object.forename }}"/>&nbsp;
            </div>

            <div class="form-group">
                <label for="id_surname">Surname:</label>&nbsp;
                <input type="text" name="surname" maxlength="64" required id="id_surname" class="form-control" value="{{ object.surname }}"/>&nbsp;
            </div>

            <input type="submit" class="btn btn-primary" value="Save">&nbsp;
            <a href="{% url 'student-list' %}" class="btn btn-success">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

core/templates/core/student_list.html
{% extends "core/base.html" %}

{% block content %}

<div class="card">
    <div class="card-header">
        <span>Student records <i class="fas fa-user"></i></span>
    </div>
    <div class="card-body">

        <table class="table table-hover table-sm">
            <thead>
            <tr>
                <th>Surname</th>
                <th>Forename</th>
            </tr>
            </thead>
            <tbody>
            {% for student in object_list %}
            <tr>
                <td><a href="{{ student.get_absolute_url }}"></i>&nbsp;{{ student.surname }}</a></td>
                <td>{{ student.forename }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

        <p><a href="{% url 'student-create' %}" class="btn btn-primary">Create new student record</a></p>

    </div>
</div>
{% endblock %}